import { test, expect } from "@playwright/test";

test("robots.txt allows crawl and points to sitemap-index", async ({ request }) => {
  const res = await request.get("/robots.txt");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toMatch(/User-agent:\s*\*/);
  expect(body).toMatch(/Allow:\s*\//);
  expect(body).toMatch(/Sitemap:\s*https:\/\/wavival\.dev\/sitemap-index\.xml/);
});

test("sitemap-index.xml is generated by @astrojs/sitemap", async ({ request }) => {
  const res = await request.get("/sitemap-index.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("<sitemapindex");
  expect(body).toContain("https://wavival.dev/sitemap-0.xml");
});

test("sitemap lists both ES and EN localized routes", async ({ request }) => {
  const res = await request.get("/sitemap-0.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  for (const loc of [
    "https://wavival.dev/",
    "https://wavival.dev/proyectos/",
    "https://wavival.dev/servicios/",
    "https://wavival.dev/sobre-mi/",
    "https://wavival.dev/contacto/",
    "https://wavival.dev/en/",
    "https://wavival.dev/en/projects/",
    "https://wavival.dev/en/services/",
    "https://wavival.dev/en/about/",
    "https://wavival.dev/en/contact/",
  ]) {
    expect(body).toContain(`<loc>${loc}</loc>`);
  }
  expect(body).not.toContain("<lastmod>");
});
